---
title: DH Paper Generator
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jamiefolsom@gmail.com
description: A paper title generator for the Digital Humanities
baseurl: http://jamiefolsom.github.io/dh-paper
url: http://jamiefolsom.github.io/dh-paper
twitter_username: jamiefolsom
github_username: jamiefolsom
markdown: kramdown
permalink: pretty
