# Site settings
title: DH Paper Generator
email: jfolsom@mit.edu
description: "A paper title generator for the Digital Humanities"
baseurl: ""
url: "http://jamiefolsom."
twitter_username: jamiefolsom
github_username:  jamiefolsom

# Build settings
markdown: kramdown
permalink: pretty
