---
title: DH Paper Generator
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hyperstudio@mit.edu
description: A paper title generator for the Digital Humanities
baseurl: http://jamiefolsom.github.io/dh-paper
url: http://jamiefolsom.github.io/dh-paper
twitter_username: mithyperstudio
github_username: hyperstudio
markdown: kramdown
permalink: pretty
